name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dockerfile.prod'
      - 'src/**'
      - 'config/**'
      - 'scripts/**'
      - 'types/**'
      - 'public/**'
      - 'data/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build . --file dockerfile.prod --tag kevinio/strapi:$(date +%s)
        docker build . --file dockerfile.prod --tag kevinio/strapi:latest
        docker build . --file dockerfile.prod --tag kevinio/strapi:${{ github.sha }}
    
    - name: Push image to Docker Hub
      if: github.event_name == 'push'
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push kevinio/strapi:latest
        docker push kevinio/strapi:${{ github.sha }}